---
- name: Install Jenkins on Fedora
  hosts: all
  become: true
  vars:
    jenkins_admin_username: admin
    jenkins_admin_password: admin123

  tasks:
    - name: Install Jenkins dependencies
      dnf:
        name:
          - java-1.8.0-openjdk-devel
          - wget
          - fontconfig
        state: present

    - name: Install Jenkins
      become_user: "{{ jenkins_admin_username }}"
      command: |
        sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
        sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        sudo dnf install -y jenkins

    - name: Set Jenkins admin username and password
      become_user: "{{ jenkins_admin_username }}"
      command: |
        sudo sh -c 'echo "{{ jenkins_admin_username }}:{{ jenkins_admin_password }}" > /var/lib/jenkins/secrets/initialAdminPassword'
